import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:spot_saver/models/park.dart';

List<Park> lisbonParks = [
  Park(
    name: "Parque do Eduardo VII",
    occupancy: 150,
    maxOccupancy: 200,
    extraInfo: "Near Marquês de Pombal Square",
    incidents: [],
    lastUpdated: DateTime.now(),
    location: const LatLng(38.732501, -9.145681),
    id: 1,
  ),
  Park(
    name: "Parque das Nações",
    occupancy: 80,
    maxOccupancy: 100,
    extraInfo: "Close to Oceanário de Lisboa",
    incidents: [],
    lastUpdated: DateTime.now(),
    location: const LatLng(38.770399, -9.096645),
    id: 2,
  ),
  Park(
    name: "Parque do Calhau",
    occupancy: 50,
    maxOccupancy: 60,
    extraInfo: "Located in Belém",
    incidents: [],
    lastUpdated: DateTime.now(),
    location: const LatLng(38.696293, -9.204273),
    id: 3,
  ),
  Park(
    name: "Parque do Tejo",
    occupancy: 30,
    maxOccupancy: 50,
    extraInfo: "Near Belém Tower",
    incidents: [],
    lastUpdated: DateTime.now(),
    location: const LatLng(38.693495, -9.213448),
    id: 4,
  ),
  Park(
    name: "Parque Eduardo VII",
    occupancy: 100,
    maxOccupancy: 120,
    extraInfo: "Close to Liberty Avenue",
    incidents: [],
    lastUpdated: DateTime.now(),
    location: const LatLng(38.728476, -9.161924),
    id: 5,
  ),
  Park(
    name: "Parque do Campo Grande",
    occupancy: 70,
    maxOccupancy: 80,
    extraInfo: "Located in Campo Grande",
    incidents: [],
    lastUpdated: DateTime.now(),
    location: const LatLng(38.759048, -9.155398),
    id: 6,
  ),
  Park(
    name: "Parque dos Poetas",
    occupancy: 90,
    maxOccupancy: 100,
    extraInfo: "In Oeiras, near Lisbon",
    incidents: [],
    lastUpdated: DateTime.now(),
    location: const LatLng(38.704876, -9.305554),
    id: 7,
  ),
  Park(
    name: "Jardim Botânico da Ajuda",
    occupancy: 40,
    maxOccupancy: 50,
    extraInfo: "Ajuda Botanical Garden",
    incidents: [],
    lastUpdated: DateTime.now(),
    location: const LatLng(38.705602, -9.197769),
    id: 8,
  ),
  Park(
    name: "Jardim da Estrela",
    occupancy: 60,
    maxOccupancy: 70,
    extraInfo: "Garden located in Campo de Ourique",
    incidents: [],
    lastUpdated: DateTime.now(),
    location: const LatLng(38.714688, -9.161156),
    id: 9,
  ),
  Park(
    name: "Jardim da Fundação Calouste Gulbenkian",
    occupancy: 80,
    maxOccupancy: 90,
    extraInfo: "Garden near Praça de Espanha",
    incidents: [],
    lastUpdated: DateTime.now(),
    location: const LatLng(38.737694, -9.154799),
    id: 10,
  ),
  Park(
    name: "Jardim do Príncipe Real",
    occupancy: 45,
    maxOccupancy: 55,
    extraInfo: "Garden in Príncipe Real neighborhood",
    incidents: [],
    lastUpdated: DateTime.now(),
    location: const LatLng(38.715081, -9.148734),
    id: 11,
  ),
  Park(
    name: "Jardim Botto Machado",
    occupancy: 20,
    maxOccupancy: 30,
    extraInfo: "Located near Santa Apolónia",
    incidents: [],
    lastUpdated: DateTime.now(),
    location: const LatLng(38.719852, -9.117448),
    id: 12,
  ),
  Park(
    name: "Jardim das Amoreiras",
    occupancy: 55,
    maxOccupancy: 65,
    extraInfo: "Garden near Amoreiras Shopping Center",
    incidents: [],
    lastUpdated: DateTime.now(),
    location: const LatLng(38.721062, -9.157168),
    id: 13,
  ),
  Park(
    name: "Jardim da Parada",
    occupancy: 25,
    maxOccupancy: 35,
    extraInfo: "Garden in Campo de Ourique",
    incidents: [],
    lastUpdated: DateTime.now(),
    location: const LatLng(38.717657, -9.165713),
    id: 14,
  ),
  Park(
    name: "Parque Urbano do Jamor",
    occupancy: 70,
    maxOccupancy: 80,
    extraInfo: "Urban park in Cruz Quebrada",
    incidents: [],
    lastUpdated: DateTime.now(),
    location: const LatLng(38.698425, -9.241458),
    id: 15,
  ),
  Park(
    name: "Parque Botânico do Monteiro-Mor",
    occupancy: 40,
    maxOccupancy: 50,
    extraInfo: "Botanical park in Lumiar",
    incidents: [],
    lastUpdated: DateTime.now(),
    location: const LatLng(38.770074, -9.152171),
    id: 16,
  ),
  Park(
    name: "Parque do Fonte Lima",
    occupancy: 30,
    maxOccupancy: 40,
    extraInfo: "Park in Alvalade",
    incidents: [],
    lastUpdated: DateTime.now(),
    location: const LatLng(38.752248, -9.145897),
    id: 17,
  ),
  Park(
    name: "Parque da Bela Vista",
    occupancy: 80,
    maxOccupancy: 90,
    extraInfo: "Park in Marvila",
    incidents: [],
    lastUpdated: DateTime.now(),
    location: const LatLng(38.746115, -9.117240),
    id: 18,
  ),
  Park(
    name: "Parque Quinta das Conchas e Lilases",
    occupancy: 65,
    maxOccupancy: 75,
    extraInfo: "Park in Lumiar",
    incidents: [],
    lastUpdated: DateTime.now(),
    location: const LatLng(38.776114, -9.150999),
    id: 19,
  ),
  Park(
    name: "Parque da Paz",
    occupancy: 45,
    maxOccupancy: 55,
    extraInfo: "Park in Almada, near Lisbon",
    incidents: [],
    lastUpdated: DateTime.now(),
    location: const LatLng(38.678636, -9.171798),
    id: 20,
  ),
];
